-- DROP DATABASE IF EXISTS
DROP DATABASE IF EXISTS EMPLOYEES_DB;
-- CREATE DATABASE 
CREATE DATABASE EMPLOYEES_DB;
-- USE DATABASE; 
USE EMPLOYEES_DB;

-- *************************** CREATE QUERIES ***********************

-- CREATE TABLE department

CREATE TABLE department(
  ID  NOT NULL INT AUTO_INCREMENT ,
  
    NAME NOT NULL VARCHAR(30) ,

    PRIMARY KEY (ID));

-- CREATE TABLE role

CREATE TABLE role(
  ID NOT NULL INTEGER(11) AUTO_INCREMENT ,
  
    TITLE NOT NULL VARCHAR(30),
  
    SALARY NOT NULL DECIMAL(11),
  
    DEPARTMENT_ID NOT NULL INT,

    PRIMARY KEY (ID)
); 


-- CREATE TABLE employee 

CREATE TABLE employee(
   ID NOT NULL AUTO_INCREMENT ,
   
    FIRST_NAME NOT NULL VARCHAR(30),
   
    LAST_NAME (ID)NOT NULL  VARCHAR(30), 
   
    ROLE_ID INT
   
    MANAGER_ID INT 

     PRIMARY KEY (ID)
);



