-- DROP DATABASE IF EXISTS
DROP DATABASE IF EXISTS EMPLOYEES_DB;
-- CREATE DATABASE 
CREATE DATABASE EMPLOYEES_DB;
-- USE DATABASE; 
USE EMPLOYEES_DB;

-- *************************** CREATE QUERIES ***********************

-- CREATE TABLE department

CREATE TABLE department(
  ID  INT PRIMARY KEY ,
  
    NAME VARCHAR(30),

-- CREATE TABLE role

CREATE TABLE role(
  ID INT PRIMARY KEY ,
  
    TITLE VARCHAR(30),
  
    SALARY DECIMAL,
  
    DEPARTMENT_ID INT,

    PRIMARY KEY (ID)
); 


-- CREATE TABLE employee 

CREATE TABLE employee(
   ID PRIMARY KEY ,
   
    FIRST_NAME VARCHAR(30),
   
    LAST_NAME (ID) VARCHAR(30), 
   
    ROLE_ID INT
   
    MANAGER_ID INT 
);



